export type Role = "member" | "leader" | "admin";
export type Status = "pending" | "approved" | "rejected" | "suspended";

export type Profile = {
  id: string;
  email: string;
  full_name: string;
  group_id: string;
  role: Role;
  status: Status;
  verification_note: string | null;
  service_years: string | null;
  bio: string | null;
  city: string | null;
  phone: string | null;
  photo_path: string | null;
  name_visibility: "group" | "all";
  contact_visibility: "leaders" | "group" | "all";
  email_forum: boolean;
  email_announcements: boolean;
  unsubscribe_token: string;
  consented_at: string | null;
  approved_at: string | null;
  member_since: number | null;
  profile_completed_at: string | null;
  created_at: string;
  first_name: string | null;
  last_name: string | null;
  job_title: string | null;
  retired: boolean;
  is_business_owner: boolean;
  business_name: string | null;
  business_website: string | null;
  business_phone: string | null;
  business_description: string | null;
  date_of_birth: string | null;
  address_line1: string | null;
  address_line2: string | null;
  state: string | null;
  postal_code: string | null;
};

// A row from member_directory(): contact fields are null when hidden.
export type DirectoryEntry = {
  id: string;
  full_name: string;
  group_id: string;
  role: Role;
  service_years: string | null;
  bio: string | null;
  city: string | null;
  photo_path: string | null;
  email: string | null;
  phone: string | null;
  member_since: number | null;
  first_name: string | null;
  last_name: string | null;
  job_title: string | null;
  retired: boolean;
  is_business_owner: boolean;
  business_name: string | null;
  business_website: string | null;
  business_phone: string | null;
  business_description: string | null;
  date_of_birth: string | null;
  address_line1: string | null;
  address_line2: string | null;
  state: string | null;
  postal_code: string | null;
  // "Month Day" when the member's personal info is visible to you.
  birthday: string | null;
};
